project:
  name: "POGOH Rebalancing"
  ramdom_seed: 42

data_collection:
  months_back: 24 #How many historical months of data to pull

features:
  test_start: '2025-02-01' #Date to split data between training and testing

models:
  hidden_layers: []
  loss_type: "mse"
  batch_size: 32
  learning_rate: 0.001