#Meta data 
experiment_name: "simple"

paths:
  raw_trips: "data/raw/pogoh_trips.parquet"
  stations: "data/raw/pogoh_stations.parquet"
  station_dist_miles: "data/raw/pogoh_station_dist_miles.parquet"
  station_dist_min: "data/raw/pogoh_station_dist_min.parquet"
  input: "data/processed/pogoh_input.parquet"

data:
  train_start_date: '2023-08-01' #Start and End dates are inclusive
  train_end_date: '2024-12-31'
  test_start_date: '2025-01-01'
  test_end_date: '2025-12-31'

training:
  batch_size: 32
  epochs: 25
  learning_rate: 1.0e-2
  decision_loss: False
  weight_decay : 1.0e-3

model:
  hidden_layers: []
  loss_demand_cost: 1   
  over_capacity_cost: 1      

sim:
  start_inv_pct: 0.5
  cutoff_hour: 24
  reset_inv: True